spring:
  datasource:
    url: jdbc:sqlserver://adhiserver.database.windows.net:1433;database=ElectronicDb;user=adhiserver;password=Elayarani@20;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30; 
    username: adhiserver
    password: Elayarani@20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191
  